
// Generated by Cadence Genus(TM) Synthesis Solution 21.17-s066_1
// Generated on: Aug  5 2025 08:01:41 EDT (Aug  5 2025 12:01:41 UTC)

// Verification Directory fv/poker_player 

module poker_player(clk, rst_n, tbl_game_start, tbl_game_over,
     cr_cmdvld, cr_cmd, cr_ack, cr_wdata, cr_rdata, cr_rdatavld,
     hand_rank_out);
  input clk, rst_n, tbl_game_start, tbl_game_over, cr_ack, cr_rdatavld;
  input [7:0] cr_rdata;
  output cr_cmdvld;
  output [2:0] cr_cmd;
  output [5:0] cr_wdata;
  output [8:0] hand_rank_out;
  wire clk, rst_n, tbl_game_start, tbl_game_over, cr_ack, cr_rdatavld;
  wire [7:0] cr_rdata;
  wire cr_cmdvld;
  wire [2:0] cr_cmd;
  wire [5:0] cr_wdata;
  wire [8:0] hand_rank_out;
  wire [5:0] \hand[4] ;
  wire [5:0] \hand[0] ;
  wire [5:0] \hand[1] ;
  wire [5:0] \hand[2] ;
  wire [5:0] \hand[3] ;
  wire [2:0] u_fsm_current_state;
  wire [2:0] u_fsm_card_counter;
  wire [5:0] stored_card;
  wire [2:0] card_index;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, cmd_done, mem_we, n_0;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_231, n_232, n_233, n_234, n_235;
  wire n_236, n_237, n_238, n_239, n_240, n_241, n_242, n_243;
  wire n_244, n_245, n_246, n_247, n_248, n_249, n_250, n_251;
  wire n_252, n_253, n_254, n_255, n_256, n_257, n_258, n_259;
  wire n_260, n_261, n_262, n_263, n_264, n_265, n_267, n_268;
  wire n_269, rank_done;
  player_interface u_player_if(.clk (clk), .rst_n (rst_n),
       .tbl_game_start (tbl_game_start), .cr_ack (cr_ack), .cr_rdata
       (cr_rdata), .cr_cmd (cr_cmd), .cr_cmdvld (cr_cmdvld), .cmd_done
       (cmd_done), .cr_wdata (cr_wdata));
  DFFRHQX1LVT \u_rank_eval_hand_rank_out_reg[0] (.RN (rst_n), .CK
       (clk), .D (n_261), .Q (hand_rank_out[0]));
  DFFRHQX1LVT \u_rank_eval_hand_rank_out_reg[1] (.RN (rst_n), .CK
       (clk), .D (n_263), .Q (hand_rank_out[1]));
  DFFRHQX1LVT \u_rank_eval_hand_rank_out_reg[2] (.RN (rst_n), .CK
       (clk), .D (n_262), .Q (hand_rank_out[2]));
  DFFRHQX1LVT \u_rank_eval_hand_rank_out_reg[3] (.RN (rst_n), .CK
       (clk), .D (n_265), .Q (hand_rank_out[3]));
  DFFRHQX1LVT \u_rank_eval_hand_rank_out_reg[4] (.RN (rst_n), .CK
       (clk), .D (n_264), .Q (hand_rank_out[4]));
  DFFRHQX1LVT \u_rank_eval_hand_rank_out_reg[5] (.RN (rst_n), .CK
       (clk), .D (n_260), .Q (hand_rank_out[5]));
  DFFRHQX1LVT \u_rank_eval_hand_rank_out_reg[6] (.RN (rst_n), .CK
       (clk), .D (n_256), .Q (hand_rank_out[6]));
  DFFRHQX1LVT \u_rank_eval_hand_rank_out_reg[7] (.RN (rst_n), .CK
       (clk), .D (n_245), .Q (hand_rank_out[7]));
  DFFRHQX1LVT \u_rank_eval_hand_rank_out_reg[8] (.RN (rst_n), .CK
       (clk), .D (n_249), .Q (hand_rank_out[8]));
  DFFRHQX1LVT u_rank_eval_rank_done_reg(.RN (rst_n), .CK (clk), .D
       (1'b1), .Q (rank_done));
  NOR2XLLVT g27224__2398(.A (n_248), .B (n_259), .Y (n_265));
  NOR2XLLVT g27225__5107(.A (n_243), .B (n_259), .Y (n_264));
  NOR2XLLVT g27226__6260(.A (n_254), .B (n_259), .Y (n_263));
  NOR2XLLVT g27227__4319(.A (n_255), .B (n_259), .Y (n_262));
  NOR2XLLVT g27228__8428(.A (n_258), .B (n_259), .Y (n_261));
  AND4XLLVT g27229__5526(.A (n_212), .B (n_246), .C (n_243), .D
       (n_257), .Y (n_260));
  NAND3BXLLVT g27230__6783(.AN (n_212), .B (n_246), .C (n_257), .Y
       (n_259));
  NAND4XLLVT g27231__3680(.A (n_248), .B (n_243), .C (n_255), .D
       (n_254), .Y (n_258));
  INVXLLVT g27233(.A (n_256), .Y (n_257));
  NOR2XLLVT g27234__1617(.A (n_248), .B (n_254), .Y (n_256));
  AOI21X1LVT g27235__2802(.A0 (n_224), .A1 (n_237), .B0 (n_253), .Y
       (n_255));
  XNOR2X1LVT g27236__1705(.A (n_224), .B (n_252), .Y (n_254));
  OAI211X1LVT g27237__5122(.A0 (n_244), .A1 (n_250), .B0 (n_233), .C0
       (n_251), .Y (n_253));
  XNOR2X1LVT g27238__8246(.A (n_237), .B (n_250), .Y (n_252));
  AOI221X1LVT g27239__7098(.A0 (n_232), .A1 (n_242), .B0 (n_213), .B1
       (n_221), .C0 (n_247), .Y (n_251));
  AOI32X1LVT g27241__6131(.A0 (n_230), .A1 (n_232), .A2 (n_241), .B0
       (n_231), .B1 (n_242), .Y (n_250));
  NOR2BX1LVT g27243__1881(.AN (n_212), .B (n_243), .Y (n_249));
  AOI21XLLVT g27244__5115(.A0 (n_225), .A1 (n_230), .B0 (n_242), .Y
       (n_247));
  NOR4X1LVT g27245__7482(.A (n_223), .B (n_229), .C (n_228), .D
       (n_236), .Y (n_248));
  INVXLLVT g27246(.A (n_245), .Y (n_246));
  NOR2X1LVT g27247__4733(.A (n_224), .B (n_237), .Y (n_244));
  OAI2BB1X1LVT g27248__6161(.A0N (n_188), .A1N (n_198), .B0 (n_240), .Y
       (n_245));
  INVXLLVT g27249(.A (n_242), .Y (n_241));
  NAND3BXLLVT g27250__9315(.AN (n_235), .B (n_204), .C (n_206), .Y
       (n_243));
  MX2X1LVT g27251__9945(.A (n_234), .B (n_239), .S0 (n_225), .Y
       (n_242));
  AOI221X1LVT g27252__2883(.A0 (n_186), .A1 (n_218), .B0 (n_200), .B1
       (n_192), .C0 (n_238), .Y (n_240));
  NOR2BX1LVT g27253__2346(.AN (n_233), .B (n_234), .Y (n_239));
  OAI211X1LVT g27254__1666(.A0 (n_197), .A1 (n_185), .B0 (n_220), .C0
       (n_219), .Y (n_238));
  OAI222X1LVT g27255__7410(.A0 (n_187), .A1 (n_214), .B0 (n_188), .B1
       (n_211), .C0 (n_208), .C1 (n_183), .Y (n_236));
  OAI211X1LVT g27256__6417(.A0 (n_168), .A1 (n_203), .B0 (n_216), .C0
       (n_217), .Y (n_235));
  XOR2XLLVT g27257__5477(.A (n_213), .B (n_221), .Y (n_237));
  INVXLLVT g27258(.A (n_232), .Y (n_231));
  NOR2X1LVT g27259__2398(.A (n_226), .B (n_222), .Y (n_234));
  NAND2XLLVT g27260__5107(.A (n_222), .B (n_226), .Y (n_233));
  OR2X1LVT g27261__6260(.A (n_60), .B (n_227), .Y (n_232));
  OAI22XLLVT g27262__4319(.A0 (n_209), .A1 (n_205), .B0 (n_199), .B1
       (n_195), .Y (n_229));
  OAI22XLLVT g27263__8428(.A0 (n_207), .A1 (n_192), .B0 (n_186), .B1
       (n_215), .Y (n_228));
  NAND2X1LVT g27264__5526(.A (n_60), .B (n_227), .Y (n_230));
  NOR2XLLVT g27265__6783(.A (n_210), .B (n_184), .Y (n_223));
  NOR2BX1LVT g27266__3680(.AN (n_188), .B (n_211), .Y (n_227));
  NOR2X1LVT g27268__1617(.A (n_206), .B (n_214), .Y (n_226));
  NAND2BX1LVT g27269__2802(.AN (n_208), .B (n_183), .Y (n_225));
  NOR2X1LVT g27270__1705(.A (n_185), .B (n_209), .Y (n_224));
  AOI22X1LVT g27271__5122(.A0 (n_201), .A1 (n_184), .B0 (n_190), .B1
       (n_195), .Y (n_220));
  AOI22XLLVT g27272__8246(.A0 (n_202), .A1 (n_183), .B0 (n_196), .B1
       (n_187), .Y (n_219));
  OAI21XLLVT g27273__7098(.A0 (n_179), .A1 (n_170), .B0 (n_181), .Y
       (n_218));
  OAI21XLLVT g27274__6131(.A0 (n_184), .A1 (n_183), .B0 (n_186), .Y
       (n_217));
  OAI21X1LVT g27275__1881(.A0 (n_184), .A1 (n_188), .B0 (n_205), .Y
       (n_216));
  NOR2X1LVT g27276__5115(.A (n_204), .B (n_207), .Y (n_222));
  NOR2BX1LVT g27277__7482(.AN (n_186), .B (n_215), .Y (n_221));
  AND2XLLVT g27278__4733(.A (n_191), .B (n_170), .Y (n_215));
  AOI22X1LVT g27279__6161(.A0 (n_175), .A1 (n_193), .B0 (n_135), .B1
       (n_159), .Y (n_214));
  NOR2X1LVT g27280__9315(.A (n_168), .B (n_199), .Y (n_213));
  OAI211X1LVT g27281__9945(.A0 (\hand[4] [2]), .A1 (n_147), .B0
       (n_176), .C0 (n_189), .Y (n_212));
  AOI22X1LVT g27282__2883(.A0 (n_169), .A1 (n_194), .B0 (n_120), .B1
       (n_157), .Y (n_211));
  AOI22X1LVT g27283__2346(.A0 (n_174), .A1 (n_172), .B0 (n_139), .B1
       (n_161), .Y (n_210));
  AOI22X1LVT g27284__1666(.A0 (n_59), .A1 (n_180), .B0 (n_138), .B1
       (n_165), .Y (n_209));
  AOI22X1LVT g27285__7410(.A0 (n_177), .A1 (n_182), .B0 (n_142), .B1
       (n_163), .Y (n_208));
  AOI22X1LVT g27286__6417(.A0 (n_171), .A1 (n_173), .B0 (n_136), .B1
       (n_167), .Y (n_207));
  INVXLLVT g27287(.A (n_187), .Y (n_206));
  INVXLLVT g27288(.A (n_185), .Y (n_205));
  INVXLLVT g27290(.A (n_192), .Y (n_204));
  INVXLLVT g27291(.A (n_183), .Y (n_203));
  OAI2BB1X1LVT g27292__5477(.A0N (n_142), .A1N (n_182), .B0 (n_177), .Y
       (n_202));
  OAI2BB1X1LVT g27293__2398(.A0N (n_139), .A1N (n_172), .B0 (n_174), .Y
       (n_201));
  OAI2BB1X1LVT g27294__5107(.A0N (n_136), .A1N (n_173), .B0 (n_171), .Y
       (n_200));
  OAI2BB1X1LVT g27295__6260(.A0N (n_157), .A1N (n_169), .B0 (n_194), .Y
       (n_198));
  AOI21XLLVT g27296__4319(.A0 (n_138), .A1 (n_180), .B0 (n_178), .Y
       (n_197));
  OAI2BB1X1LVT g27297__8428(.A0N (n_135), .A1N (n_175), .B0 (n_193), .Y
       (n_196));
  AOI22X1LVT g27298__5526(.A0 (n_152), .A1 (n_153), .B0 (n_137), .B1
       (n_150), .Y (n_199));
  INVXLLVT g27299(.A (n_168), .Y (n_195));
  NAND2BXLLVT g27300__6783(.AN (n_179), .B (n_181), .Y (n_191));
  OAI2BB1X1LVT g27301__3680(.A0N (n_137), .A1N (n_152), .B0 (n_153), .Y
       (n_190));
  MX2XLLVT g27302__1617(.A (n_148), .B (n_151), .S0 (\hand[0] [2]), .Y
       (n_189));
  NAND3BXLLVT g27303__2802(.AN (n_118), .B (n_119), .C (n_156), .Y
       (n_194));
  NAND3X1LVT g27304__1705(.A (n_100), .B (n_99), .C (n_158), .Y
       (n_193));
  XNOR2X1LVT g27305__5122(.A (n_136), .B (n_167), .Y (n_192));
  XNOR2X1LVT g27306__8246(.A (n_120), .B (n_157), .Y (n_188));
  XNOR2X1LVT g27307__7098(.A (n_135), .B (n_159), .Y (n_187));
  XNOR2X1LVT g27308__6131(.A (n_143), .B (n_155), .Y (n_186));
  XOR2XLLVT g27309__1881(.A (n_138), .B (n_165), .Y (n_185));
  XNOR2X1LVT g27310__5115(.A (n_139), .B (n_161), .Y (n_184));
  XNOR2X1LVT g27311__7482(.A (n_142), .B (n_163), .Y (n_183));
  INVXLLVT g27312(.A (n_59), .Y (n_178));
  NAND4XLLVT g27313__4733(.A (\hand[0] [2]), .B (\hand[1] [1]), .C
       (\hand[1] [2]), .D (n_146), .Y (n_176));
  OR2XLLVT g27314__6161(.A (n_133), .B (n_162), .Y (n_182));
  NAND2X1LVT g27315__9315(.A (n_130), .B (n_154), .Y (n_181));
  NAND2BX1LVT g27316__9945(.AN (n_164), .B (n_132), .Y (n_180));
  NOR2X1LVT g27317__2883(.A (n_130), .B (n_154), .Y (n_179));
  NAND2X1LVT g27319__2346(.A (n_133), .B (n_162), .Y (n_177));
  AO21X1LVT g27320__1666(.A0 (n_99), .A1 (n_100), .B0 (n_158), .Y
       (n_175));
  NAND2X1LVT g27321__7410(.A (n_128), .B (n_160), .Y (n_174));
  OR2X1LVT g27322__6417(.A (n_131), .B (n_166), .Y (n_173));
  OR2XLLVT g27323__5477(.A (n_128), .B (n_160), .Y (n_172));
  NAND2X1LVT g27324__2398(.A (n_131), .B (n_166), .Y (n_171));
  NAND2XLLVT g27325__5107(.A (n_143), .B (n_155), .Y (n_170));
  OR2XLLVT g27326__6260(.A (n_127), .B (n_156), .Y (n_169));
  XOR2XLLVT g27327__4319(.A (n_137), .B (n_150), .Y (n_168));
  ADDFX1LVT g27328__8428(.A (n_95), .B (n_91), .CI (n_87), .CO (n_166),
       .S (n_167));
  ADDFX1LVT g27329__5526(.A (n_116), .B (n_111), .CI (n_90), .CO
       (n_164), .S (n_165));
  ADDFX1LVT g27330__6783(.A (n_117), .B (n_110), .CI (n_93), .CO
       (n_162), .S (n_163));
  ADDFX1LVT g27331__3680(.A (n_96), .B (n_108), .CI (n_89), .CO
       (n_160), .S (n_161));
  ADDFX1LVT g27332__1617(.A (n_94), .B (n_113), .CI (n_92), .CO
       (n_158), .S (n_159));
  ADDFX1LVT g27333__2802(.A (n_112), .B (n_109), .CI (n_134), .CO
       (n_156), .S (n_157));
  ADDFX1LVT g27334__1705(.A (n_97), .B (n_107), .CI (n_88), .CO
       (n_154), .S (n_155));
  NAND2X1LVT g27335__5122(.A (n_129), .B (n_149), .Y (n_153));
  OR4X1LVT g27336__8246(.A (\hand[1] [1]), .B (\hand[2] [1]), .C
       (n_65), .D (n_144), .Y (n_151));
  OR2XLLVT g27337__7098(.A (n_129), .B (n_149), .Y (n_152));
  ADDFX1LVT g27338__6131(.A (n_114), .B (n_106), .CI (n_115), .CO
       (n_149), .S (n_150));
  NAND4XLLVT g27339__1881(.A (\hand[1] [1]), .B (\hand[2] [1]), .C
       (n_65), .D (n_141), .Y (n_148));
  OR4X1LVT g27340__5115(.A (\hand[1] [1]), .B (\hand[2] [1]), .C
       (\hand[1] [2]), .D (n_140), .Y (n_147));
  NOR2BX1LVT g27342__7482(.AN (\hand[2] [1]), .B (n_58), .Y (n_146));
  OR2X1LVT g27345__4733(.A (n_269), .B (n_268), .Y (n_267));
  NAND4XLLVT g27347__6161(.A (\hand[2] [2]), .B (\hand[3] [2]), .C
       (\hand[4] [2]), .D (n_104), .Y (n_144));
  NOR4X1LVT g27348__9315(.A (\hand[2] [2]), .B (\hand[4] [2]), .C
       (\hand[3] [2]), .D (n_105), .Y (n_141));
  NAND3BXLLVT g27349__9945(.AN (\hand[0] [2]), .B (n_77), .C (n_104),
       .Y (n_140));
  OAI31X1LVT g27350__2883(.A0 (cr_rdata[0]), .A1 (cr_rdata[1]), .A2
       (n_98), .B0 (n_8), .Y (n_269));
  XNOR2X1LVT g27351__2346(.A (n_124), .B (n_56), .Y (n_143));
  XNOR2X1LVT g27352__1666(.A (n_126), .B (n_55), .Y (n_142));
  XNOR2X1LVT g27353__7410(.A (n_118), .B (n_119), .Y (n_134));
  XNOR2X1LVT g27354__6417(.A (n_125), .B (n_103), .Y (n_139));
  XNOR2X1LVT g27355__5477(.A (n_123), .B (n_57), .Y (n_138));
  XNOR2X1LVT g27356__2398(.A (n_121), .B (n_122), .Y (n_137));
  XNOR2X1LVT g27357__5107(.A (n_101), .B (n_102), .Y (n_136));
  XOR2XLLVT g27358__6260(.A (n_100), .B (n_99), .Y (n_135));
  NOR2BX1LVT g27359__4319(.AN (n_55), .B (n_126), .Y (n_133));
  NAND2BX1LVT g27360__8428(.AN (n_57), .B (n_123), .Y (n_132));
  NOR2BX1LVT g27361__5526(.AN (n_102), .B (n_101), .Y (n_131));
  NOR2BX1LVT g27362__6783(.AN (n_119), .B (n_118), .Y (n_127));
  NOR2BX1LVT g27363__3680(.AN (n_124), .B (n_56), .Y (n_130));
  NOR2BX1LVT g27364__1617(.AN (n_121), .B (n_122), .Y (n_129));
  NOR2BX1LVT g27365__2802(.AN (n_103), .B (n_125), .Y (n_128));
  NAND2X1LVT g27366__1705(.A (\hand[3] [4]), .B (n_70), .Y (n_126));
  AND2X1LVT g27367__5122(.A (n_83), .B (\hand[2] [4]), .Y (n_117));
  NAND2X1LVT g27368__8246(.A (\hand[0] [3]), .B (n_73), .Y (n_125));
  NOR2X1LVT g27369__7098(.A (\hand[0] [3]), .B (n_74), .Y (n_124));
  NOR2XLLVT g27370__6131(.A (\hand[3] [4]), .B (n_80), .Y (n_123));
  NOR2XLLVT g27371__1881(.A (\hand[2] [4]), .B (n_69), .Y (n_116));
  NOR2XLLVT g27372__5115(.A (n_62), .B (n_72), .Y (n_115));
  NAND2BX1LVT g27373__7482(.AN (n_74), .B (\hand[0] [3]), .Y (n_122));
  NOR2X1LVT g27374__4733(.A (n_64), .B (n_80), .Y (n_121));
  NOR2BX1LVT g27375__6161(.AN (n_71), .B (\hand[4] [3]), .Y (n_120));
  NOR2BX1LVT g27376__9315(.AN (n_73), .B (\hand[0] [3]), .Y (n_119));
  NAND2X1LVT g27377__9945(.A (n_64), .B (n_70), .Y (n_118));
  NOR2X1LVT g27378__2883(.A (n_61), .B (n_86), .Y (n_114));
  NOR2X1LVT g27379__2346(.A (\hand[4] [3]), .B (n_68), .Y (n_113));
  NOR2BX1LVT g27380__1666(.AN (n_75), .B (\hand[1] [4]), .Y (n_112));
  NOR2XLLVT g27381__7410(.A (\hand[1] [4]), .B (n_86), .Y (n_111));
  AND2X1LVT g27382__6417(.A (n_75), .B (\hand[1] [4]), .Y (n_110));
  NOR2BX1LVT g27383__5477(.AN (n_83), .B (\hand[2] [4]), .Y (n_109));
  AND2X1LVT g27384__2398(.A (n_71), .B (\hand[4] [3]), .Y (n_108));
  NOR2X1LVT g27385__5107(.A (\hand[4] [3]), .B (n_72), .Y (n_107));
  NOR2X1LVT g27386__6260(.A (n_63), .B (n_69), .Y (n_106));
  OR4X1LVT g27388__4319(.A (cr_rdata[2]), .B (cr_rdata[3]), .C
       (cr_rdata[4]), .D (cr_rdata[5]), .Y (n_98));
  NAND3X1LVT g27389__8428(.A (\hand[4] [1]), .B (\hand[0] [1]), .C
       (\hand[3] [1]), .Y (n_105));
  NOR3X1LVT g27390__5526(.A (\hand[3] [1]), .B (\hand[0] [1]), .C
       (\hand[4] [1]), .Y (n_104));
  NOR2X1LVT g27391__6783(.A (\hand[3] [4]), .B (n_78), .Y (n_103));
  NOR2X1LVT g27392__3680(.A (n_63), .B (n_76), .Y (n_97));
  NOR2X1LVT g27393__1617(.A (\hand[2] [4]), .B (n_79), .Y (n_96));
  NOR2X1LVT g27395__2802(.A (n_64), .B (n_78), .Y (n_102));
  NOR2X1LVT g27396__1705(.A (n_63), .B (n_79), .Y (n_95));
  NAND2X1LVT g27398__5122(.A (\hand[0] [3]), .B (n_66), .Y (n_101));
  NOR2X1LVT g27399__8246(.A (\hand[2] [4]), .B (n_76), .Y (n_94));
  NOR2X1LVT g27401__7098(.A (\hand[4] [3]), .B (n_84), .Y (n_93));
  NOR2X1LVT g27402__6131(.A (\hand[1] [4]), .B (n_81), .Y (n_92));
  NOR2X1LVT g27403__1881(.A (n_62), .B (n_84), .Y (n_91));
  NOR2X1LVT g27404__5115(.A (\hand[0] [3]), .B (n_85), .Y (n_100));
  NOR2X1LVT g27405__7482(.A (n_62), .B (n_68), .Y (n_90));
  NOR2X1LVT g27406__4733(.A (\hand[3] [4]), .B (n_82), .Y (n_99));
  NOR2X1LVT g27407__6161(.A (\hand[1] [4]), .B (n_67), .Y (n_89));
  NOR2X1LVT g27408__9315(.A (n_61), .B (n_81), .Y (n_88));
  NOR2X1LVT g27409__9945(.A (n_61), .B (n_67), .Y (n_87));
  NAND2X1LVT g27413__2883(.A (\hand[1] [5]), .B (\hand[1] [3]), .Y
       (n_86));
  NOR2XLLVT g27414__2346(.A (\hand[2] [2]), .B (\hand[3] [2]), .Y
       (n_77));
  NAND2BX1LVT g27415__1666(.AN (\hand[0] [4]), .B (\hand[0] [5]), .Y
       (n_85));
  NAND2BX1LVT g27416__7410(.AN (\hand[4] [5]), .B (\hand[4] [4]), .Y
       (n_84));
  NOR2X1LVT g27417__6417(.A (\hand[2] [5]), .B (\hand[2] [3]), .Y
       (n_83));
  NAND2BX1LVT g27418__5477(.AN (\hand[3] [3]), .B (\hand[3] [5]), .Y
       (n_82));
  NAND2BX1LVT g27419__2398(.AN (\hand[1] [3]), .B (\hand[1] [5]), .Y
       (n_81));
  NAND2X1LVT g27420__5107(.A (\hand[3] [5]), .B (\hand[3] [3]), .Y
       (n_80));
  NAND2BX1LVT g27421__6260(.AN (\hand[2] [5]), .B (\hand[2] [3]), .Y
       (n_79));
  NAND2BX1LVT g27422__4319(.AN (\hand[3] [5]), .B (\hand[3] [3]), .Y
       (n_78));
  NAND2BX1LVT g27424__8428(.AN (\hand[2] [3]), .B (\hand[2] [5]), .Y
       (n_76));
  NOR2X1LVT g27425__5526(.A (\hand[1] [5]), .B (\hand[1] [3]), .Y
       (n_75));
  NAND2XLLVT g27426__6783(.A (\hand[0] [5]), .B (\hand[0] [4]), .Y
       (n_74));
  NOR2X1LVT g27427__3680(.A (\hand[0] [4]), .B (\hand[0] [5]), .Y
       (n_73));
  NAND2X1LVT g27428__1617(.A (\hand[4] [4]), .B (\hand[4] [5]), .Y
       (n_72));
  NOR2X1LVT g27429__2802(.A (\hand[4] [4]), .B (\hand[4] [5]), .Y
       (n_71));
  NAND2BX1LVT g27430__1705(.AN (u_fsm_current_state[2]), .B
       (u_fsm_current_state[1]), .Y (n_268));
  NOR2X1LVT g27431__5122(.A (\hand[3] [5]), .B (\hand[3] [3]), .Y
       (n_70));
  NAND2X1LVT g27432__8246(.A (\hand[2] [5]), .B (\hand[2] [3]), .Y
       (n_69));
  NAND2BX1LVT g27433__7098(.AN (\hand[4] [4]), .B (\hand[4] [5]), .Y
       (n_68));
  NAND2BX1LVT g27434__6131(.AN (\hand[1] [5]), .B (\hand[1] [3]), .Y
       (n_67));
  NOR2BX1LVT g27435__1881(.AN (\hand[0] [4]), .B (\hand[0] [5]), .Y
       (n_66));
  INVXLLVT g27436(.A (\hand[1] [2]), .Y (n_65));
  INVX1LVT g27437(.A (\hand[3] [4]), .Y (n_64));
  INVX1LVT g27438(.A (\hand[2] [4]), .Y (n_63));
  INVX1LVT g27439(.A (\hand[4] [3]), .Y (n_62));
  INVX1LVT g27440(.A (\hand[1] [4]), .Y (n_61));
  NOR2BX1LVT g2__5115(.AN (n_184), .B (n_210), .Y (n_60));
  NAND2BX1LVT g27441__7482(.AN (n_132), .B (n_164), .Y (n_59));
  NAND4BX1LVT g27442__4733(.AN (n_105), .B (\hand[2] [2]), .C
       (\hand[3] [2]), .D (\hand[4] [2]), .Y (n_58));
  NAND2BX1LVT g27443__6161(.AN (n_85), .B (\hand[0] [3]), .Y (n_57));
  NAND2BX1LVT g27444__9315(.AN (n_82), .B (\hand[3] [4]), .Y (n_56));
  NOR2BX1LVT g27445__9945(.AN (n_66), .B (\hand[0] [3]), .Y (n_55));
  DFFRHQX1LVT \u_fsm_card_counter_reg[2] (.RN (rst_n), .CK (clk), .D
       (n_54), .Q (u_fsm_card_counter[2]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[3][5] (.RN (rst_n), .CK (clk), .D
       (stored_card[5]), .SI (\hand[3] [5]), .SE (n_39), .Q
       (\hand[3] [5]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[3][4] (.RN (rst_n), .CK (clk), .D
       (stored_card[4]), .SI (\hand[3] [4]), .SE (n_39), .Q
       (\hand[3] [4]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[3][1] (.RN (rst_n), .CK (clk), .D
       (stored_card[1]), .SI (\hand[3] [1]), .SE (n_39), .Q
       (\hand[3] [1]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[3][2] (.RN (rst_n), .CK (clk), .D
       (stored_card[2]), .SI (\hand[3] [2]), .SE (n_39), .Q
       (\hand[3] [2]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[3][3] (.RN (rst_n), .CK (clk), .D
       (stored_card[3]), .SI (\hand[3] [3]), .SE (n_39), .Q
       (\hand[3] [3]));
  INVXLLVT g24884(.A (n_53), .Y (n_54));
  AOI32X1LVT g24885__2883(.A0 (n_18), .A1 (u_fsm_card_counter[1]), .A2
       (u_fsm_card_counter[0]), .B0 (n_48), .B1
       (u_fsm_card_counter[2]), .Y (n_53));
  AOI31X1LVT g24886__2346(.A0 (n_17), .A1 (n_25), .A2 (n_39), .B0
       (tbl_game_start), .Y (n_52));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[1][3] (.RN (rst_n), .CK (clk), .D
       (\hand[1] [3]), .SI (stored_card[3]), .SE (n_40), .Q
       (\hand[1] [3]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[1][5] (.RN (rst_n), .CK (clk), .D
       (\hand[1] [5]), .SI (stored_card[5]), .SE (n_40), .Q
       (\hand[1] [5]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[1][4] (.RN (rst_n), .CK (clk), .D
       (\hand[1] [4]), .SI (stored_card[4]), .SE (n_40), .Q
       (\hand[1] [4]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[1][1] (.RN (rst_n), .CK (clk), .D
       (\hand[1] [1]), .SI (stored_card[1]), .SE (n_40), .Q
       (\hand[1] [1]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[1][2] (.RN (rst_n), .CK (clk), .D
       (\hand[1] [2]), .SI (stored_card[2]), .SE (n_40), .Q
       (\hand[1] [2]));
  OAI31X1LVT g24892__1666(.A0 (n_267), .A1 (u_fsm_card_counter[1]), .A2
       (n_5), .B0 (n_43), .Y (n_51));
  OAI222X1LVT g24893__7410(.A0 (n_13), .A1 (n_16), .B0 (n_33), .B1
       (u_fsm_current_state[0]), .C0 (n_4), .C1 (n_31), .Y (n_50));
  DFFSX2LVT \u_hand_mem_hand_reg[0][1] (.SN (1'b1), .CK (clk), .D
       (n_47), .Q (\hand[0] [1]), .QN (UNCONNECTED));
  SDFFRHQX1LVT \u_fsm_card_counter_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_3), .SI (n_35), .SE (u_fsm_card_counter[0]), .Q
       (u_fsm_card_counter[0]));
  DFFSX2LVT \u_hand_mem_hand_reg[0][4] (.SN (1'b1), .CK (clk), .D
       (n_44), .Q (\hand[0] [4]), .QN (UNCONNECTED0));
  DFFSX2LVT \u_hand_mem_hand_reg[0][3] (.SN (1'b1), .CK (clk), .D
       (n_45), .Q (\hand[0] [3]), .QN (UNCONNECTED1));
  DFFSX2LVT \u_hand_mem_hand_reg[0][2] (.SN (1'b1), .CK (clk), .D
       (n_46), .Q (\hand[0] [2]), .QN (UNCONNECTED2));
  DFFSX2LVT \u_hand_mem_hand_reg[0][5] (.SN (1'b1), .CK (clk), .D
       (n_49), .Q (\hand[0] [5]), .QN (UNCONNECTED3));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[2][5] (.RN (rst_n), .CK (clk), .D
       (stored_card[5]), .SI (\hand[2] [5]), .SE (n_30), .Q
       (\hand[2] [5]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[2][4] (.RN (rst_n), .CK (clk), .D
       (stored_card[4]), .SI (\hand[2] [4]), .SE (n_30), .Q
       (\hand[2] [4]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[2][1] (.RN (rst_n), .CK (clk), .D
       (stored_card[1]), .SI (\hand[2] [1]), .SE (n_30), .Q
       (\hand[2] [1]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[2][2] (.RN (rst_n), .CK (clk), .D
       (stored_card[2]), .SI (\hand[2] [2]), .SE (n_30), .Q
       (\hand[2] [2]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[2][3] (.RN (rst_n), .CK (clk), .D
       (stored_card[3]), .SI (\hand[2] [3]), .SE (n_30), .Q
       (\hand[2] [3]));
  DFFRHQX1LVT \u_fsm_current_state_reg[2] (.RN (rst_n), .CK (clk), .D
       (n_37), .Q (u_fsm_current_state[2]));
  MX2XLLVT g24907__6417(.A (\hand[0] [5]), .B (stored_card[5]), .S0
       (n_0), .Y (n_49));
  OAI21XLLVT g24908__5477(.A0 (u_fsm_card_counter[1]), .A1
       (u_fsm_current_state[2]), .B0 (n_42), .Y (n_48));
  MX2XLLVT g24909__2398(.A (\hand[0] [1]), .B (stored_card[1]), .S0
       (n_0), .Y (n_47));
  MX2XLLVT g24910__5107(.A (\hand[0] [2]), .B (stored_card[2]), .S0
       (n_0), .Y (n_46));
  MX2XLLVT g24911__6260(.A (\hand[0] [3]), .B (stored_card[3]), .S0
       (n_0), .Y (n_45));
  MX2XLLVT g24912__4319(.A (\hand[0] [4]), .B (stored_card[4]), .S0
       (n_0), .Y (n_44));
  NAND2X1LVT g24913__8428(.A (n_41), .B (u_fsm_card_counter[1]), .Y
       (n_43));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[4][2] (.RN (rst_n), .CK (clk), .D
       (\hand[4] [2]), .SI (stored_card[2]), .SE (n_26), .Q
       (\hand[4] [2]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[4][1] (.RN (rst_n), .CK (clk), .D
       (\hand[4] [1]), .SI (stored_card[1]), .SE (n_26), .Q
       (\hand[4] [1]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[4][4] (.RN (rst_n), .CK (clk), .D
       (\hand[4] [4]), .SI (stored_card[4]), .SE (n_26), .Q
       (\hand[4] [4]));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[4][3] (.RN (rst_n), .CK (clk), .D
       (\hand[4] [3]), .SI (stored_card[3]), .SE (n_26), .Q
       (\hand[4] [3]));
  DFFRHQX1LVT \card_index_reg[0] (.RN (rst_n), .CK (clk), .D (n_36), .Q
       (card_index[0]));
  INVXLLVT g24920(.A (n_41), .Y (n_42));
  NOR2X1LVT g24921__5526(.A (tbl_game_start), .B (n_29), .Y (n_38));
  NAND4XLLVT g24922__6783(.A (n_12), .B (n_16), .C (n_23), .D (n_22),
       .Y (n_37));
  SDFFRHQX1LVT \u_hand_mem_hand_reg[4][5] (.RN (rst_n), .CK (clk), .D
       (\hand[4] [5]), .SI (stored_card[5]), .SE (n_26), .Q
       (\hand[4] [5]));
  OAI211X1LVT g24924__3680(.A0 (u_fsm_current_state[2]), .A1
       (u_fsm_card_counter[0]), .B0 (n_32), .C0
       (u_fsm_current_state[1]), .Y (n_41));
  NOR3X1LVT g24925__1617(.A (card_index[1]), .B (card_index[2]), .C
       (n_15), .Y (n_40));
  NAND3BXLLVT g24926__2802(.AN (card_index[2]), .B (card_index[1]), .C
       (n_14), .Y (n_39));
  NOR2X1LVT g24927__1705(.A (tbl_game_start), .B (n_28), .Y (n_36));
  NAND2X1LVT g24928__5122(.A (n_32), .B (u_fsm_current_state[1]), .Y
       (n_35));
  OAI221X1LVT g24929__8246(.A0 (u_fsm_current_state[1]), .A1 (n_8), .B0
       (u_fsm_current_state[0]), .B1 (n_4), .C0 (n_31), .Y (n_34));
  AOI32X1LVT g24930__7098(.A0 (u_fsm_card_counter[0]), .A1 (n_6), .A2
       (n_19), .B0 (tbl_game_start), .B1 (n_4), .Y (n_33));
  SDFFRHQX1LVT \u_fsm_stored_card_reg_reg[4] (.RN (rst_n), .CK (clk),
       .D (cr_rdata[4]), .SI (stored_card[4]), .SE (n_267), .Q
       (stored_card[4]));
  SDFFRHQX1LVT \u_fsm_stored_card_reg_reg[3] (.RN (rst_n), .CK (clk),
       .D (cr_rdata[3]), .SI (stored_card[3]), .SE (n_267), .Q
       (stored_card[3]));
  SDFFRHQX1LVT \u_fsm_stored_card_reg_reg[2] (.RN (rst_n), .CK (clk),
       .D (cr_rdata[2]), .SI (stored_card[2]), .SE (n_267), .Q
       (stored_card[2]));
  SDFFRHQX1LVT \u_fsm_stored_card_reg_reg[5] (.RN (rst_n), .CK (clk),
       .D (cr_rdata[5]), .SI (stored_card[5]), .SE (n_267), .Q
       (stored_card[5]));
  SDFFRHQX1LVT \u_fsm_stored_card_reg_reg[1] (.RN (rst_n), .CK (clk),
       .D (cr_rdata[1]), .SI (stored_card[1]), .SE (n_267), .Q
       (stored_card[1]));
  INVXLLVT g24937(.A (n_27), .Y (n_32));
  AOI22X1LVT g24938__6131(.A0 (n_9), .A1 (n_14), .B0 (card_index[1]),
       .B1 (n_15), .Y (n_29));
  AOI22XLLVT g24939__1881(.A0 (n_17), .A1 (n_20), .B0 (n_11), .B1
       (card_index[0]), .Y (n_28));
  OAI211X1LVT g24940__5115(.A0 (n_7), .A1 (u_fsm_current_state[2]), .B0
       (n_16), .C0 (n_22), .Y (n_27));
  NAND2X1LVT g24941__7482(.A (u_fsm_current_state[0]), .B (n_24), .Y
       (n_31));
  NAND3BXLLVT g24942__4733(.AN (n_21), .B (card_index[1]), .C (n_10),
       .Y (n_30));
  NAND2XLLVT g24943__6161(.A (card_index[2]), .B (n_15), .Y (n_25));
  NOR2X1LVT g24944__9315(.A (n_17), .B (n_21), .Y (n_26));
  OAI21X1LVT g24945__9945(.A0 (rank_done), .A1
       (u_fsm_current_state[2]), .B0 (n_22), .Y (n_24));
  NAND3BXLLVT g24946__2883(.AN (n_268), .B (rank_done), .C
       (u_fsm_current_state[0]), .Y (n_23));
  INVXLLVT g24947(.A (n_21), .Y (n_20));
  NOR2BX1LVT g24948__2346(.AN (u_fsm_card_counter[2]), .B (n_268), .Y
       (n_19));
  NOR2XLLVT g24949__1666(.A (n_267), .B (u_fsm_card_counter[2]), .Y
       (n_18));
  NAND2BX1LVT g24950__7410(.AN (tbl_game_over), .B
       (u_fsm_current_state[2]), .Y (n_22));
  OR2XLLVT g24951__6417(.A (n_11), .B (card_index[0]), .Y (n_21));
  INVXLLVT g24952(.A (n_15), .Y (n_14));
  NOR2X1LVT g24953__5477(.A (cr_ack), .B (n_4), .Y (n_13));
  NAND2XLLVT g24954__2398(.A (u_fsm_current_state[2]), .B (n_4), .Y
       (n_12));
  NAND2X1LVT g24955__5107(.A (card_index[2]), .B (n_9), .Y (n_17));
  NAND2X1LVT g24956__6260(.A (u_fsm_current_state[2]), .B (n_8), .Y
       (n_16));
  NAND2X1LVT g24957__4319(.A (mem_we), .B (card_index[0]), .Y (n_15));
  INVXLLVT g24962(.A (n_269), .Y (n_7));
  INVXLLVT g24964(.A (u_fsm_card_counter[0]), .Y (n_5));
  INVXLLVT g24969(.A (n_267), .Y (n_3));
  NOR4BX1LVT g27446__8428(.AN (rst_n), .B (card_index[1]), .C
       (card_index[2]), .D (n_21), .Y (n_0));
  DFFRX1LVT u_fsm_mem_we_reg_reg(.RN (rst_n), .CK (clk), .D (n_3), .Q
       (mem_we), .QN (n_11));
  DFFRX1LVT \card_index_reg[2] (.RN (rst_n), .CK (clk), .D (n_52), .Q
       (card_index[2]), .QN (n_10));
  DFFRX1LVT \card_index_reg[1] (.RN (rst_n), .CK (clk), .D (n_38), .Q
       (card_index[1]), .QN (n_9));
  DFFRX1LVT \u_fsm_current_state_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_50), .Q (u_fsm_current_state[0]), .QN (n_8));
  DFFRX1LVT \u_fsm_card_counter_reg[1] (.RN (rst_n), .CK (clk), .D
       (n_51), .Q (u_fsm_card_counter[1]), .QN (n_6));
  DFFRX1LVT \u_fsm_current_state_reg[1] (.RN (rst_n), .CK (clk), .D
       (n_34), .Q (u_fsm_current_state[1]), .QN (n_4));
endmodule

